name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ Instalar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ğŸ“¦ Instalar Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2

      - name: ğŸ“ Instalar dependÃªncias com Poetry
        run: poetry install

      - name: âœ… Rodar isort (verificar ordenaÃ§Ã£o de imports)
        run: poetry run isort . --check-only

      - name: âœ… Rodar black (verificar formataÃ§Ã£o)
        run: poetry run black . --check

      - name: ğŸ§ª Rodar testes com pytest
        run: poetry run pytest
